<?php

$isDebug = false;

$data = [
    'select_country' => 'Select Country',
    'delete' => 'Delete',
    'save' => 'Save',
    'edit' => 'Edit',
    'add_params' => 'Add new parameters',
    'country' => 'Country',
    'add_country' => 'Add your Country',
    'add_country_desc' => 'Add new connection between Country and App',
    'list_linkcountry' => 'List of Connections',
    'user' => 'User',
    'app' => 'App',
    'archived' => 'Archived',
    'params' => 'Parameters',
    'name' => 'Name',
    'package' => 'Package',
    'status' => 'Status',
    'model' => 'Model',
    'brand' => 'Brand',
    'resolution' => 'Resolution',
    'device_language' => 'Devices Language',
    'date_reg' => 'Date of registration ',
    'linkcountry_id' =>  'ID connections',
    'device_id' => 'Device ID',
    'server_response' => 'Server Response',
    'filterlog_id' => 'Filter Log ID',
    'date' => 'Date',
    'add_app' => 'Add App',
    'add_app_desc' => 'Add new App',
    'my_app' => 'My apps',
    'my_app_desc' => 'My Apps Dashboard',
    'no_published' => 'Not Published',
    'published' => 'Published',
    'banned' => 'Banned',
    'ready' => 'Ready',
    'testing' => 'Testing',
    'revision' => 'Revision',
    'Black list' => 'Black list',
    'in_black' => 'In black list',
    'in_white' => 'In white list',
    'no_list' => 'Off the list',
    'list_status' => 'List status',
    'link' => 'Link',
    'actions' => 'Actons',
    'open_app' => 'Open Your App',
    'edit_app' => 'Edit Your App',
    'check_status' => 'Check status',
    'visits_stats' => 'Visiting Staticstics',
    'visits_stats_desc' => 'Visiting Statistics Dashboard',
    'ask_delete_app' => 'Do you really want to delete this App?',
    'ask_delete_linkcountry' => 'Do you really want to delete this connectiothis appis not p?',
    'information_googleplay' => 'Google Play Information',
    'filter_country' => 'Countries Filter',
    'author' => 'Author',
    'category' => 'Category',
    'android_version' => 'Android version',
    'rating' => 'Rating',
    'voted' => 'Voted',
    'size' => 'Size',
    'downloads' => 'Downloads',
    'version' => ' Current Version',
    'content_rating' => 'Content Rating',
    'last_update' => 'Last Update',
    'policy' => 'Privacy Policy',
    'app_deleted_googleplay' => 'Sorry, this App was removed from Google Play (Ban)',
    'app_no_published_googleplay' => 'This app is not published in Google Play yet',
    'country_distribution' => 'Country Distribution',
    'logs' => 'Logs',
    'edit_linkcountry' => 'Edit Country Connection',
    'edit_linkcountry_desc' => 'Edit Country Connection with this App',
    'visits' => 'Amount of Visits',
    'uniq' => 'Unique',
    'bots' => 'Bots',
    'active_country' => 'Active Countries',
    'exit_account' => 'Exit',
    'lang_interface' => 'Language',
    'server_time' => 'Server Time',
    'global_filter' => 'Global Filters',
    'cloaking' => 'Cloaking',
    'deeplinks' => 'Deeplinks',
    'add_deeplink' => 'Add new Deeplink',
    'active_deeplinks' => 'Active Deeplinks',
    'key' => 'Key',
    'value' => 'Value',
    'url' => 'URL',
    'pcs' => 'Pcs.',
    'url_for_webview' => 'Active WebView URL',
    'date_start' => 'From',
    'date_end' => 'To',
    'price' => 'Installation Cost',
    'total_price' => 'Total Cost',
    'user_country' => 'User Country',
    'all_country' => 'All Countries',
    'access_token' => 'Access Token',
    'partner_balance' => 'Partner balance',
    'comment' => 'Comment',
    'source_key1' => 'Key',
    'push_ev' => 'Push events',
];



if($isDebug){
    foreach ($data as $key=>$value){
        $data[$key] = $value."_localized";
    }
}

return $data;